# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='CreateUser',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='created_at',
            new_name='created_at_mod',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='email',
            new_name='email_mod',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='first_name',
            new_name='first_name_mod',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='last_name',
            new_name='last_name_mod',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='password',
            new_name='password_mod',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='updated_at',
            new_name='updated_at_mod',
        ),
    ]
