# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_auto_20180221_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createuser',
            old_name='created_at_mod',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='email_mod',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='first_name_mod',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='last_name_mod',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='password_mod',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='createuser',
            old_name='updated_at_mod',
            new_name='updated_at',
        ),
    ]
