# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-22 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0004_loginuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateUser',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
