# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=14)),
                ('description', models.CharField(max_length=255)),
                ('userid', models.CharField(max_length=255)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(related_name='userFaves', to='coursesapp.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='userAdded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAdds', to='coursesapp.User'),
        ),
    ]
