# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0002_auto_20180228_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite', to='coursesapp.User'),
        ),
    ]
