# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=255)),
                ('myusername', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('hiredate', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='add_to_list_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAdds', to='beltapp.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='wishitems',
            field=models.ManyToManyField(related_name='userWishes', to='beltapp.User'),
        ),
    ]
